# Generated by Django 4.1 on 2022-09-24 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passcode_ingredient", models.TextField(blank=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecureItemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud"),
                            ("social media", "Social media"),
                            ("credit card", "Credit card"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("aws", "AWS"),
                            ("linode", "Linode"),
                            ("digital ocean", "Digital ocean"),
                            ("heroku", "Heroku"),
                            ("app password", "App password"),
                            ("github", "Github"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "Linkedin"),
                            ("visa card", "Visa card"),
                            ("store id", "Store id"),
                            ("id card", "Id card"),
                            ("credit card", "Credit card"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=100,
                    ),
                ),
                ("the_key", models.TextField(blank=True, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("i_label", models.CharField(max_length=255)),
                ("i_username", models.TextField(blank=True, null=True)),
                ("i_phone", models.CharField(blank=True, max_length=100, null=True)),
                ("i_email", models.EmailField(blank=True, max_length=300, null=True)),
                ("i_password", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "i_passphrase",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("i_api", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "i_ssh_key_pub",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "i_ssh_key_prt",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("i_card_no", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "i_card_valid_range",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("i_card_ccv", models.CharField(blank=True, max_length=300, null=True)),
                ("i_card_pin", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "i_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureapp.securepass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSecretIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.TextField(blank=True, null=True)),
                (
                    "rely_on",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureapp.secureiteminfo",
                    ),
                ),
                (
                    "trusted_people",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trusted_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("the_hash", models.TextField(blank=True, null=True)),
                ("the_private", models.TextField(blank=True, null=True)),
                (
                    "rely_on",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureapp.secureiteminfo",
                    ),
                ),
            ],
        ),
    ]
