# Generated by Django 4.1 on 2022-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secureiteminfo",
            name="platform",
            field=models.CharField(
                choices=[
                    ("aws", "AWS"),
                    ("linode", "Linode"),
                    ("digital ocean", "Digital ocean"),
                    ("heroku", "Heroku"),
                    ("app password", "App password"),
                    ("github", "Github"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                    ("linkedin", "Linkedin"),
                    ("visa card", "Visa card"),
                    ("store id", "Store id"),
                    ("id card", "Id card"),
                    ("credit card", "Credit card"),
                    ("custom", "Custom"),
                ],
                max_length=100,
            ),
        ),
    ]
