# Generated by Django 4.1 on 2022-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0002_alter_secureiteminfo_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secureiteminfo",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("organisation", "Organisation"),
                ],
                default="public",
                max_length=100,
            ),
        ),
    ]
