# Generated by Django 4.1 on 2022-10-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0006_alter_category_platform_list_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category_platform_list",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="secureapp.categories"
            ),
        ),
    ]
