# Generated by Django 4.1 on 2022-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0007_alter_category_platform_list_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secureiteminfo",
            name="visibility",
            field=models.CharField(default="private", max_length=100),
        ),
    ]
