# Generated by Django 4.1 on 2022-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0008_alter_secureiteminfo_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="secureiteminfo",
            name="custom_platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
