# Generated by Django 4.1 on 2022-10-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("secureapp", "0009_secureiteminfo_custom_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platforms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("platform_key", models.CharField(max_length=255)),
                ("platform_value", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secureapp.categories",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category_Platform_List",
        ),
    ]
