# Generated by Django 4.1 on 2022-10-02 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("secureapp", "0010_platforms_delete_category_platform_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="secureiteminfo",
            name="trusted_user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
